set-bash-profile $option="windows":
   #!/bin/bash
   link_path=$HOME/.bashrc.d/k7-profile
   target_path=/usr/share/k7/bash-profiles/$option
   if [[ $option == "off" ]]; then
       rm $link_path
       exit
   fi

   if [[ ! -d $HOME/.bashrc.d ]]; then
       mkdir $HOME/.bashrc.d
   fi

   if [[ ! -f $target_path ]]; then
       echo "{{ RED }}'$option' is not valid {{ NORMAL }}"
       echo "$(ls /usr/share/k7/bash-profiles) off"
       exit 1
   fi

   if [[ -f $link_path ]]; then
       rm $link_path
   fi

   ln -s $target_path $link_path
   echo "{{GREEN}}Bash profile set to '$option'."

_write-kvantum-config:
    #!/bin/bash
    kv_path=~/.config/Kvantum/kvantum.kvconfig
    mkdir -p ~/.config/Kvantum
    if [[ ! -f $kv_path ]]; then
        echo -e "[General]\ntheme=Windows7Aero" > $kv_path
    else
        echo "File already exists"
    fi
