set-bash-profile $option="choose":
   #!/bin/bash
   OPTIONS=("cmdprompt fastfetch off")
   if [[ $option == "choose" ]]; then
       echo -e "cmdprompt = Win7 command prompt.\nublue = Ublue's Message of the Day prompt\nfastfetch = Fastfetch\noff = No prompt"
       option=$(gum choose $OPTIONS)
   fi

   if [[ $(echo $OPTIONS | sed "s/$option//g") == $OPTIONS ]]; then
       echo "Invalid option '$option':"
       echo $OPTIONS
       exit 1
   fi

   case $option in
       cmdprompt)
           gum confirm "Would you like to enable command prompt PS1? ( ex. C:\var\home\\${USER}> )" && \
           7just _set-config win-7-prompt 1 && \
           echo "{{GREEN+BOLD}}Command Prompt PS1 enabled.{{NORMAL}}"
       ;;
   esac

   7just _set-config bash-profile $option
   echo "{{GREEN+BOLD}}Bash profile set to '$option'. Open a new terminal to see the changes.{{NORMAL}}"

toggle-win7-ps1:
    #!/bin/bash
    if [[ $(7just _get-config win-7-prompt) == "1" ]]; then
        7just _set-config win-7-prompt 0
        echo "{{GREEN+BOLD}}Command Prompt PS1 disabled. Open a new terminal to see changes.{{NORMAL}}"
    else
        7just _set-config win-7-prompt 1
        echo "{{GREEN+BOLD}}Command Prompt PS1 enabled. Open a new terminal to see changes.{{NORMAL}}"
    fi


toggle-fastfetch-alias:
    #!/bin/bash
    if [[ $(7just _get-config no-fastfetch-alias) == "1" ]]; then
        7just _set-config  no-fastfetch-alias 0
        echo "{{GREEN+BOLD}}Fastfetch alias disabled.{{NORMAL}}"
    else
        7just _set-config no-fastfetch-alias 1
        echo "{{GREEN+BOLD}}Fastfetch alias enabled. Open a new terminal to see changes.{{NORMAL}}"
    fi

set-cmd-prompt-konsole-theme:
   #!/bin/bash
   konsole_path=~/.local/share/konsole/

   gum confirm "{{YELLOW+BOLD}}This will overwrite your konsole config. Would you like to continue?{{NORMAL}}"
   mkdir -p $konsole_path
   if [[ ! -f $konsole_path/Kinoite7.profile ]]; then
       echo "{{BOLD}}Wrting Kinoite7 konsole profile{{NORMAL}}"
       ln -s /usr/share/kin7/config/konsole.profile $konsole_path/Kinoite7.profile
   fi
   
   echo "{{BOLD}}Writing konsole config{{NORMAL}}"
   cat /usr/share/kin7/config/konsolerc > ~/.config/konsolerc

   echo "{{GREEN+BOLD}}Done. Open konsole again to see changes.{{NORMAL}}"

_kin7-init:
    #!/bin/bash
    init_file=~/.config/kin7-initialized
    if [[ -f $init_file ]]; then exit fi

    7just _write-kvantum-config
    mkdir -p ~/.config
    touch ~/.config/no-show-user-motd
    touch $init_file


_write-kvantum-config:
    #!/bin/bash
    kv_path=~/.config/Kvantum/kvantum.kvconfig
    mkdir -p ~/.config/Kvantum
    if [[ ! -f $kv_path ]]; then
        echo -e "[General]\ntheme=Windows7Aero" > $kv_path
    else
        echo "File already exists"
    fi

_set-config $key $value:
    #!/bin/bash
    mkdir -p ~/.config/kin7
    echo "$value" > ~/.config/kin7/$key

_get-config $key $default_value="":
    #!/bin/bash
    mkdir -p ~/.config/kin7
    if [[ ! -f ~/.config/kin7/$key ]]; then
        echo "$default_value"
        exit
    fi
    
    cat ~/.config/kin7/$key

